# Please keep AllCops, Bundler, Style, Metrics groups and then order cops
# alphabetically
inherit_from:
  - https://raw.githubusercontent.com/hanami/devtools/master/.rubocop.yml
AllCops:
  Exclude:
    - "vendor/**/*"
    - "lib/hanami/assets/compressors/*"
    - "**/*.gemspec"
Style/CommentedKeyword:
  Exclude:
    - "spec/**/*.rb"
Naming/MethodParameterName:
  AllowedNames:
    - as
